# Generated by Django 4.0.3 on 2022-04-22 14:31

import datetime
import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_verificationlink_expire_at_report_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.message'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='neutral.png', null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/'), upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='verificationlink',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 15, 1, 49, 918786, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='verificationlink',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
