# Generated by Django 4.0.3 on 2022-06-29 12:51

import app.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_image_alter_verificationlink_expire_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='last_message',
        ),
        migrations.AddField(
            model_name='message',
            name='from_match',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='app.match'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='./neutral.png', null=True, upload_to=app.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='verificationlink',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 13, 21, 1, 347849, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'user_target')},
        ),
    ]
