# Generated by Django 4.0.5 on 2022-07-03 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_match_last_message_message_from_match_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_match',
        ),
        migrations.AddField(
            model_name='match',
            name='messages',
            field=models.ManyToManyField(blank=True, to='app.message'),
        ),
        migrations.AlterField(
            model_name='verificationlink',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 14, 30, 44, 881881, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('user', 'match_user')},
        ),
    ]
