# Generated by Django 4.0.5 on 2022-07-03 14:46

import app.models
import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_message_from_match_match_messages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='messages',
        ),
        migrations.AddField(
            model_name='match',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='testmsg', verbose_name=app.models.Message), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='verificationlink',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 15, 16, 15, 811532, tzinfo=utc)),
        ),
    ]
