# Generated by Django 4.0.5 on 2022-07-03 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_match_messages_match_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationlink',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 16, 2, 58, 283372, tzinfo=utc)),
        ),
    ]
