# Generated by Django 4.0.5 on 2022-07-03 15:39

import app.models
import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_verificationlink_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='testmsg', max_length=255, verbose_name=app.models.Message), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(default='test', max_length=255),
        ),
        migrations.AlterField(
            model_name='verificationlink',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 16, 9, 3, 155905, tzinfo=utc)),
        ),
    ]
