# Generated by Django 4.0.5 on 2022-07-04 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_match_messages_alter_message_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lf_criteria',
            field=models.CharField(choices=[('A', 'Appearences'), ('F', 'First Sight love'), ('L', 'Alchemy'), ('U', 'Undecided')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='lf_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='verificationlink',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 19, 0, 15, 396107, tzinfo=utc)),
        ),
    ]
