# Generated by Django 4.0.5 on 2022-07-05 20:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_lf_criteria_alter_user_lf_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='messages',
        ),
        migrations.AddField(
            model_name='message',
            name='match',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.match'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationlink',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 21, 5, 10, 920143, tzinfo=utc)),
        ),
    ]
