# Generated by Django 4.0.5 on 2022-07-06 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_match_messages_message_match_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reason',
        ),
        migrations.AlterField(
            model_name='verificationlink',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 12, 41, 9, 992509, tzinfo=utc)),
        ),
    ]
