# Generated by Django 4.0.5 on 2022-07-06 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_report_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationlink',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 12, 41, 27, 616969, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
